version: '3'
services:
    web:
        build:
            context: ./freshcuts_server
        image: fc_web:latest
        command: bundle exec rails s -p 3000 -b '0.0.0.0' -e production
        env_file: ./freshcuts_server/.env
        volumes:
          - ./freshcuts_server:/freshcuts
        ports:
         - "3001:3000"
        depends_on:
         - db
         - solr
        environment:
         - VIRTUAL_HOST=fc.daemon.me.uk

    solr:
        build: 
            context: ./freshcuts_solr
        image: fc_solr:latest
        volumes:
            - ./freshcuts_data/solr:/opt/solr/server/solr
        ports:
         - "8983:8983"
    db:
        image: postgres:9.6.3-alpine
        environment:
            - PGDATA=/pgdata
        volumes:
            - ./freshcuts_data/pgdata:/pgdata
        ports:
         - '5431:5432'
    nginx-proxy:
        image: jwilder/nginx-proxy:alpine
        container_name: nginx-proxy
        ports:
         - '80:80'
        volumes:
         - /var/run/docker.sock:/tmp/docker.sock:ro


